[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "imaging-knime-to-galaxy"
version = "0.1.0"
description = "A python framework to convert KNIME workflows to Galaxy."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab",
    "openai",
    "numpy",
    "planemo",
    "sentence-transformers>=2.7.0",
    "huggingface_hub",
    "ipywidgets",
    "torch<=2.2.2; sys_platform == 'darwin' and platform_machine == 'x86_64'",
]

[tool.uv]
constraint-dependencies = [
    "cryptography<49; sys_platform == 'darwin' and platform_machine == 'x86_64'",
]

required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",
]